### ISSUE TITLE
Migrate from `tarpaulin` to `llvm-cov`for code coverage checks

### ISSUE THREAD

**Issue by dclause** [dclause/hermes-five#26]
**Motivation**
`tarpaulin` produces incomplete or inaccurate coverage reports, especially for complex cases (async, macros, etc.).
The goal is to switch to a more robust and modern solution: `llvm-cov`.

**Objectives**
- [ ] Update the GitHub Actions coverage workflow to use llvm-cov instead of tarpaulin.
- [ ] Upload coverage results to Codecov using the lcov format generated by llvm-cov.
- [ ] Limit coverage workflow runs to once a week and/or manual triggers to stay within quota.

_Example GitHub Actions triggers:_
```yaml
on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at 00:00 UTC
  workflow_dispatch:     # manual trigger support
```

**Notes**
- Use nightly attributes for none coverable code:
  - inject a `cfg_attr` in the case of a nightly build:
`#![cfg_attr(coverage_nightly, feature(coverage_attribute))]`
  - use `coverage(off)` with this nightly feature:
`#[cfg_attr(coverage_nightly, coverage(off))]`

- Recommended local command to run tests with coverage and open an HTML report in the browser:
`cargo +nightly llvm-cov --package hermes-five --package hermes-five-macros-internals --html --open`
